services:
  db:
    container_name: 'images-mysql'
    image: 'mysql:8.0'
    env_file:
      - .env
    environment:
      - 'MYSQL_DATABASE=kaju_db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'